kind: pipeline
name: jsunit

steps:
  - name: vue-build
    image: nextcloudci/node:node-4
    commands:
      - find js/ -type f -delete
      - npm install
      - npm run build
      - git status
      - bash -c "[[ ! \"`git status --porcelain js/`\" ]] || ( echo 'Uncommited changes in vue build' && exit 1 )"

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
